import 'package:flutter/material.dart';

class FeaturedPlaylist {
  final String id;
  final String title;
  final String subtitle;
  final List<Color> gradient;
  final IconData icon;
  final String emoji;

  /// If set, fetch from a real YouTube playlist via /playlist?id=
  final String? playlistId;

  /// Used only when playlistId is null — fires in parallel, 1 result each.
  final List<String> searchQueries;

  /// Results per query (search mode only). Keep at 1 to guarantee no dupes.
  final int limitPerQuery;

  /// Max songs to fetch (playlist mode only).
  final int playlistLimit;

  const FeaturedPlaylist({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.gradient,
    required this.icon,
    required this.emoji,
    this.playlistId,
    this.searchQueries = const [],
    this.limitPerQuery = 1,
    this.playlistLimit = 50,
  });

  bool get isPlaylistMode => playlistId != null;

  /// First search query — used for card thumbnail preview in search mode
  String get searchQuery =>
      searchQueries.isNotEmpty ? searchQueries.first : title;
}

// ─────────────────────────────────────────────────────────────────────────────
// Featured playlists — ALL search-query mode, limitPerQuery: 1
// ─────────────────────────────────────────────────────────────────────────────

const kFeaturedPlaylists = [
  // ── Top 50 Bollywood ──────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'bollywood_top50',
    title: 'Top 50 Bollywood',
    subtitle: 'Hottest Hindi hits',
    gradient: [Color(0xFFFF6B6B), Color(0xFFFF8E53)],
    icon: Icons.local_fire_department_rounded,
    emoji: '🎬',
    limitPerQuery: 1,
    searchQueries: [
      'Kesariya Brahmastra official audio Arijit Singh',
      'Satranga Animal official audio Arijit Singh',
      'Tere Vaaste official audio Varun Jain Sachet Tandon',
      'Jhoome Jo Pathaan official audio Arijit Singh',
      'Chaleya Jawan official audio Arijit Singh',
      'Zinda Banda Jawan official audio Anirudh',
      'Apna Bana Le Bhediya official audio Arijit Singh',
      'Phir Aur Kya Chahiye Zara Hatke official audio',
      'Sajni Laapataa Ladies official audio Arijit Singh',
      'Nain Tare Crew official audio Diljit Dosanjh',
      'Ranjha Shershaah official audio Jasleen Royal',
      'Raataan Lambiyan Shershaah official audio Jubin Nautiyal',
      'Ghungroo War official audio Arijit Singh',
      'Tera Yaar Hoon Main Sonu Ke Titu Ki Sweety official audio',
      'Baarish Ban Jaana official audio Payal Dev Stebin',
      'Lag Ja Gale Raazi official audio Rekha Bhardwaj',
      'Dil Bechara title track official audio AR Rahman',
      'Shayad Love Aaj Kal official audio Arijit Singh',
      'Lahore Guru Randhawa official audio',
      'Tenu Lehenga Satyameva Jayate 2 official audio',
      'Rowdy Baby Maari 2 official audio Dhanush',
      'Srivalli Pushpa official audio Sid Sriram',
      'Oo Antava Pushpa official audio Samantha',
      'Naatu Naatu RRR official audio',
      'Butta Bomma Ala Vaikunthapurramuloo official audio',
      'Ramuloo Ramulaa Ala Vaikunthapurramuloo official audio',
      'Manike Mage Hithe Hindi official audio',
      'Kahani Sunao Payal Dev official audio',
      'Mehendi Wala Haath Darshan Raval official audio',
      'Ik Vaari Aa Raabta official audio Arijit Singh',
      'Yeh Tune Kya Kiya Once Upon A Time official audio',
      'Agar Tum Saath Ho Tamasha official audio Arijit Singh',
    ],
  ),

  // ── Top 50 English ────────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'english_top50',
    title: 'Top 50 English',
    subtitle: 'Global chart toppers',
    gradient: [Color(0xFF6C63FF), Color(0xFF3B82F6)],
    icon: Icons.music_note_rounded,
    emoji: '🌍',
    limitPerQuery: 1,
    searchQueries: [
      'APT Rose Bruno Mars official audio',
      'Die With A Smile Lady Gaga Bruno Mars official audio',
      'Birds Of A Feather Billie Eilish official audio',
      'Good Luck Babe Chappell Roan official audio',
      'Espresso Sabrina Carpenter official audio',
      'Please Please Please Sabrina Carpenter official audio',
      'Too Sweet Hozier official audio',
      'Beautiful Things Benson Boone official audio',
      'luther Kendrick Lamar SZA official audio',
      'Blinding Lights The Weeknd official audio',
      'Levitating Dua Lipa official audio',
      'As It Was Harry Styles official audio',
      'Anti-Hero Taylor Swift official audio',
      'Flowers Miley Cyrus official audio',
      'Unholy Sam Smith Kim Petras official audio',
      'Rich Flex Drake 21 Savage official audio',
      'Calm Down Rema Selena Gomez official audio',
      'Cruel Summer Taylor Swift official audio',
      'Watermelon Sugar Harry Styles official audio',
      'Save Your Tears The Weeknd official audio',
      'Stay The Kid LAROI Justin Bieber official audio',
      'Heat Waves Glass Animals official audio',
      'Shivers Ed Sheeran official audio',
      'Peaches Justin Bieber Daniel Caesar Giveon official audio',
      'Bad Habits Ed Sheeran official audio',
      'Industry Baby Lil Nas X Jack Harlow official audio',
      'Butter BTS official audio',
      'Dynamite BTS official audio',
      'Easy On Me Adele official audio',
      'My Universe Coldplay BTS official audio',
      'Shape of You Ed Sheeran official audio',
      'Rolling in the Deep Adele official audio',
    ],
  ),

  // ── Top 50 Bengali ────────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'bengali_top50',
    title: 'Top 50 Bengali',
    subtitle: 'Best of Bangla music',
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    icon: Icons.queue_music_rounded,
    emoji: '🎶',
    limitPerQuery: 1,
    searchQueries: [
      'Ekla Cholo Re Rabindranath Tagore official audio',
      'Amar Sonar Bangla official audio Rabindra Sangeet',
      'Amaro Porano Jaha Chay Rabindranath official audio',
      'Tumi Robe Nirobe Rabindranath official audio',
      'Jodi Tor Dak Shune Keu Na Ase official audio Tagore',
      'Aguner Poroshmoni official audio Tagore',
      'Ebar Phirao More official audio Rabindranath',
      'Amar Hiyar Majhe official audio Tagore',
      'Nishi Raat Baake Re official audio Manna Dey Bengali',
      'Tomake Chai official audio Shreya Ghoshal Bengali',
      'Mon Majhi Re official audio Bengali film',
      'Hoyto Tomari Jonno official audio Bengali',
      'Tumi Je Amar official audio Bengali romantic',
      'Bristir Dhara official audio Bengali modern',
      'Meghla Akash official audio Bengali',
      'Bolchi Tomar Kaane Kaane official audio Bengali',
      'Tumi Sundor Tobe official audio Rabindra Sangeet',
      'Shukno Patar official audio Bengali modern',
      'Phire Esho official audio Bengali',
      'Pagla Hawar Badh official audio Bengali folk',
      'Aamar Bhalobasha official audio Bengali',
      'O Amar Desher Mati official audio Bengali',
      'Brishti Pore Tapur Tupur official audio Bengali',
      'Nil Akasher Neechey official audio Bengali classic',
      'Chand Mama official audio Bengali',
      'Purulia Nachna Re official audio Bengali folk',
      'Emon Ekta Maa De Bangla official audio',
      'Nodir Kule official audio Bengali folk',
      'Aaj Baar Maago official audio Bengali',
      'Tumi Amar Prothom official audio Bengali',
      'Bristi Bristi official audio Bengali modern',
      'Shono Ekti Mujiborer Thekey official audio',
    ],
  ),

  // ── 90s Bollywood ─────────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: '90s_bollywood',
    title: '90s Bollywood',
    subtitle: 'Nostalgia overloaded',
    gradient: [Color(0xFF42275A), Color(0xFF734B6D)],
    icon: Icons.history_rounded,
    emoji: '📼',
    limitPerQuery: 1,
    searchQueries: [
      'Kuch Kuch Hota Hai title song official audio',
      'Tujhe Yaad Na Meri Aayi Kuch Kuch Hota Hai official audio',
      'Pehla Nasha Jo Jeeta Wohi Sikandar official audio',
      'Dil Hai Ke Manta Nahin official audio Mohammad Aziz',
      'Tip Tip Barsa Pani Mohra official audio',
      'Tu Cheez Badi Hai Mast Mast Mohra official audio',
      'Ek Do Teen Tezaab official audio Madhuri Dixit',
      'Tujhe Dekha To Dilwale Dulhania Le Jayenge official audio',
      'Mehndi Laga Ke Rakhna DDLJ official audio',
      'Mere Khwabon Mein DDLJ official audio',
      'Bole Chudiyan Kabhi Khushi Kabhie Gham official audio',
      'Suraj Hua Madham K3G official audio',
      'You Are My Soniya K3G official audio',
      'Ole Ole Yeh Dillagi official audio Saif Ali Khan',
      'Didi Tera Devar Deewana Hum Aapke Hain Koun official audio',
      'Pehla Pehla Pyaar Hum Aapke Hain Koun official audio',
      'Aati Kya Khandala Ghulam official audio',
      'Ek Pal Ka Jeena Kaho Naa Pyaar Hai official audio',
      'Hum Dil De Chuke Sanam title song official audio',
      'Nimbooda Hum Dil De Chuke Sanam official audio',
      'Main Koi Aisa Geet Gaoon Kabhi Na Kabhi official audio',
      'Yaaron Dosti KK official audio',
      'Kehna Hi Kya Bombay official audio AR Rahman',
      'Tu Hi Re Bombay official audio Hariharan',
      'Roja Janeman official audio AR Rahman',
      'Dil Se Re Dil Se official audio Shah Rukh Khan',
      'Chaiyya Chaiyya Dil Se official audio Sukhwinder',
      'Ek Ladki Ko Dekha Toh Aisa Laga 1942 Love Story official audio',
      'Kya Mujhe Pyaar Hai Woh Lamhe official audio',
      'Aankhon Ki Gustakhiyan Hum Dil De Chuke official audio',
      'Woh Ladki Jo Sarfarosh official audio',
      'Pehli Nazar Mein Pyaar Ho Gaya official audio',
    ],
  ),

  // ── Hindi Romantic ────────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'hindi_romantic',
    title: 'Hindi Romantic',
    subtitle: 'Love songs collection',
    gradient: [Color(0xFFED213A), Color(0xFF93291E)],
    icon: Icons.favorite_rounded,
    emoji: '❤️',
    limitPerQuery: 1,
    searchQueries: [
      'Tum Hi Ho Aashiqui 2 official audio Arijit Singh',
      'Channa Mereya ADHM official audio Arijit Singh',
      'Hawayein Jab Harry Met Sejal official audio Arijit Singh',
      'Tera Ban Jaunga Kabir Singh official audio',
      'Tujhe Kitna Chahne Lage Kabir Singh official audio',
      'Bekhayali Kabir Singh official audio Sachet Tandon',
      'Ae Dil Hai Mushkil title official audio Arijit Singh',
      'Bulleya Sultan official audio Arijit Singh',
      'Bol Do Na Zara Azhar official audio Armaan Malik',
      'Phir Kabhi MS Dhoni official audio Arijit Singh',
      'Pehli Baar Dil Dhadakne Do official audio Arijit Singh',
      'Jeena Jeena Badlapur official audio Atif Aslam',
      'Tu Jo Mila Highway official audio Arijit Singh',
      'Pashmina Fitoor official audio Arijit Singh',
      'Dil Diyan Gallan Tiger Zinda Hai official audio',
      'Naina Dangal official audio Arijit Singh',
      'Khairiyat Chhichhore official audio Arijit Singh',
      'Qaafirana Kedarnath official audio Arijit Singh',
      'Pehli Nazar Mein Race official audio Atif Aslam',
      'Woh Lamhe Jab We Met official audio Atif Aslam',
      'Tu Jaane Na Ajab Prem Ki Ghazab Kahani official audio',
      'Ik Fiqaa Fanaa official audio Shafqat Amanat Ali',
      'Yeh Tune Kya Kiya Once Upon A Time official audio',
      'Agar Tum Saath Ho Tamasha official audio Arijit Singh',
      'Gerua Dilwale official audio Shah Rukh Khan',
      'Ik Vaari Aa Raabta official audio Arijit Singh',
      'Mere Naam Tu Zero official audio Shah Rukh Khan',
      'Jag Ghoomeya Sultan official audio Rahat Fateh Ali Khan',
      'Suno Na Sangemarmar Youngistaan official audio',
      'Sun Saathiya ABCD 2 official audio',
      'Tere Liye Prince official audio Atif Aslam',
      'Main Hoon Hero Tera Hero official audio Salman Khan',
    ],
  ),

  // ── International Pop ─────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'international_pop',
    title: 'International Pop',
    subtitle: 'World\'s biggest pop hits',
    gradient: [Color(0xFF00B4DB), Color(0xFF0083B0)],
    icon: Icons.public_rounded,
    emoji: '🌟',
    limitPerQuery: 1,
    searchQueries: [
      'Shape of You Ed Sheeran official audio',
      'Uptown Funk Bruno Mars Mark Ronson official audio',
      'Happy Pharrell Williams official audio',
      'Roar Katy Perry official audio',
      'Firework Katy Perry official audio',
      'Rolling in the Deep Adele official audio',
      'Someone Like You Adele official audio',
      'Hello Adele official audio',
      'Stay Rihanna Mikky Ekko official audio',
      'We Found Love Rihanna Calvin Harris official audio',
      'Diamonds Rihanna official audio',
      'Sorry Justin Bieber official audio',
      'Love Yourself Justin Bieber official audio',
      'Shake It Off Taylor Swift official audio',
      'Blank Space Taylor Swift official audio',
      'Counting Stars OneRepublic official audio',
      'Radioactive Imagine Dragons official audio',
      'Demons Imagine Dragons official audio',
      'Thunder Imagine Dragons official audio',
      'Girls Like You Maroon 5 official audio',
      'Sugar Maroon 5 official audio',
      'Animals Maroon 5 official audio',
      'Waka Waka Shakira official audio',
      'Hips Don\'t Lie Shakira official audio',
      'Senorita Shawn Mendes Camila Cabello official audio',
      'Havana Camila Cabello official audio',
      'Despacito Luis Fonsi Daddy Yankee official audio',
      'Cheap Thrills Sia official audio',
      'Chandelier Sia official audio',
      'Blinding Lights The Weeknd official audio',
      'Save Your Tears The Weeknd official audio',
      'Levitating Dua Lipa official audio',
    ],
  ),

  // ── Arijit Singh Hits ─────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'arijit_hits',
    title: 'Arijit Singh Hits',
    subtitle: 'The king of melody',
    gradient: [Color(0xFFFC5C7D), Color(0xFF6A3093)],
    icon: Icons.mic_rounded,
    emoji: '🎤',
    limitPerQuery: 1,
    searchQueries: [
      'Tum Hi Ho Arijit Singh official audio Aashiqui 2',
      'Channa Mereya Arijit Singh official audio ADHM',
      'Ae Dil Hai Mushkil Arijit Singh official audio',
      'Hawayein Arijit Singh official audio Jab Harry Met Sejal',
      'Tera Ban Jaunga Arijit Singh official audio Kabir Singh',
      'Kesariya Arijit Singh official audio Brahmastra',
      'Satranga Arijit Singh official audio Animal',
      'Apna Bana Le Arijit Singh official audio Bhediya',
      'Phir Aur Kya Chahiye Arijit Singh official audio Zara Hatke',
      'Naina Arijit Singh official audio Dangal',
      'Sajni Arijit Singh official audio Laapataa Ladies',
      'Chaleya Arijit Singh official audio Jawan',
      'Ranjha Arijit Singh official audio Shershaah',
      'Raataan Lambiyan Arijit Singh official audio Shershaah',
      'Dil Diyan Gallan Arijit Singh official audio Tiger Zinda Hai',
      'Ik Vaari Aa Arijit Singh official audio Raabta',
      'Gerua Arijit Singh official audio Dilwale',
      'Khairiyat Arijit Singh official audio Chhichhore',
      'Kalank title song Arijit Singh official audio',
      'Hamari Adhuri Kahani Arijit Singh official audio',
      'Aayat Arijit Singh official audio Bajirao Mastani',
      'Tujhe Kitna Chahne Lage Arijit Singh official audio Kabir Singh',
      'Bekhayali Arijit Singh official audio Kabir Singh',
      'Pehli Baar Arijit Singh official audio Dil Dhadakne Do',
      'Bulleya Arijit Singh official audio Sultan',
      'Soch Na Sake Arijit Singh official audio Airlift',
      'Meri Aashiqui Arijit Singh official audio Aashiqui 2',
      'Tu Jaane Na Arijit Singh official audio Ajab Prem',
      'Pashmina Arijit Singh official audio Fitoor',
      'Duaa Arijit Singh official audio Shanghai',
    ],
  ),

  // ── Sa Re Ga Ma Pa ────────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'saregama_pa',
    title: 'Sa Re Ga Ma Pa',
    subtitle: 'All time classics',
    gradient: [Color(0xFFF7971E), Color(0xFFFFD200)],
    icon: Icons.star_rounded,
    emoji: '⭐',
    limitPerQuery: 1,
    searchQueries: [
      'Lata Mangeshkar Lag Ja Gale official audio',
      'Kishore Kumar Mere Sapno Ki Rani official audio',
      'Mohammed Rafi Baharon Phool Barsao official audio',
      'Asha Bhosle Dum Maro Dum official audio',
      'Lata Mangeshkar Ajeeb Dastan Hai Yeh official audio',
      'Kishore Kumar Pal Pal Dil Ke Paas official audio',
      'Mohammed Rafi Abhi Na Jao Chhod Kar official audio',
      'Mukesh Kabhi Kabhi Mere Dil official audio',
      'Lata Mangeshkar Tere Bina Zindagi official audio',
      'Kishore Kumar Roop Tera Mastana official audio',
      'Asha Bhosle Piya Tu Ab To Aaja official audio',
      'Mohammed Rafi Din Dhal Jaye official audio',
      'Lata Mangeshkar Aaja Sanam Madhur Chandni official audio',
      'Kishore Kumar Yeh Shaam Mastani official audio',
      'Mohammed Rafi Dil Ke Jharokhe Mein official audio',
      'Kishore Kumar Zindagi Ek Safar official audio',
      'Mohammed Rafi Teri Galiyon Mein official audio',
      'Asha Bhosle In Aankhon Ki Masti official audio',
      'Mukesh Mera Joota Hai Japani official audio',
      'Lata Mangeshkar Pyar Kiya To Darna Kya official audio',
      'Kishore Kumar Kuch To Log Kahenge official audio',
      'Mohammed Rafi Chahe Koi Mujhe Junglee Kahe official audio',
      'Asha Bhosle Chura Liya Hai Tumne official audio',
      'Lata Mangeshkar Woh Shaam Kuch Ajeeb Thi official audio',
      'Kishore Kumar Musafir Hoon Yaaron official audio',
      'Mohammed Rafi Ek Hasina Thi official audio',
      'Lata Mangeshkar Ae Mere Watan Ke Logon official audio',
      'Mukesh Jeena Yahan Marna Yahan official audio',
      'Asha Bhosle Yeh Mera Dil Yaar Ka Diwana official audio',
      'Mohammed Rafi Yeh Chand Sa Roshan Chehra official audio',
    ],
  ),

  // ── Bollywood Mashups ─────────────────────────────────────────────────────
  FeaturedPlaylist(
    id: 'bollywood_mashups',
    title: 'Bollywood Mashups',
    subtitle: 'Best remix & party mixes',
    gradient: [Color(0xFFFF9966), Color(0xFFFF5E62)],
    icon: Icons.merge_rounded,
    emoji: '🎛️',
    limitPerQuery: 3,
    searchQueries: [
      'bollywood mashup 2024 DJ Chetas official',
      'hindi party mashup 2024 DJ Notorious official',
      'Arijit Singh mashup 2024 official audio',
      'Punjabi mashup 2024 nonstop official',
      'Love mashup 2024 bollywood romantic official',
      'bollywood nonstop mashup 2025 official',
      'hindi hits mashup 2025 official',
      'retro bollywood mashup official',
      '90s bollywood mashup official',
      'best of bollywood mashup 2024 official',
    ],
  ),
];

// ─────────────────────────────────────────────────────────────────────────────
// Mood playlists — search mode, limitPerQuery:1
// ─────────────────────────────────────────────────────────────────────────────

const kMoodPlaylists = [
  FeaturedPlaylist(
    id: 'mood_workout',
    title: 'Workout',
    subtitle: 'High energy, push harder',
    gradient: [Color(0xFFFF416C), Color(0xFFFF4B2B)],
    icon: Icons.fitness_center_rounded,
    emoji: '💪',
    limitPerQuery: 1,
    searchQueries: [
      'Eye of the Tiger Survivor official video',
      'Lose Yourself Eminem official video',
      'Till I Collapse Eminem official audio',
      'Stronger Kanye West official video',
      'Power Kanye West official video',
      'Run The World Beyonce official video',
      'Work Hard Play Hard Wiz Khalifa official',
      'Thunderstruck ACDC official video',
      'Remember The Name Fort Minor official video',
      'Jump Around House of Pain official video',
      'Can\'t Hold Us Macklemore official video',
      'Radioactive Imagine Dragons official video',
      'Centuries Fall Out Boy official video',
      'Warriors Imagine Dragons official video',
      'Seven Nation Army White Stripes official video',
    ],
  ),
  FeaturedPlaylist(
    id: 'mood_chill',
    title: 'Chill',
    subtitle: 'Relax and unwind',
    gradient: [Color(0xFF4776E6), Color(0xFF8E54E9)],
    icon: Icons.self_improvement_rounded,
    emoji: '😌',
    limitPerQuery: 1,
    searchQueries: [
      'River Flows In You Yiruma official piano',
      'The Night We Met Lord Huron official audio',
      'Experience Ludovico Einaudi official audio',
      'Nuvole Bianche Ludovico Einaudi official audio',
      'Skinny Love Bon Iver official audio',
      'Holocene Bon Iver official video',
      'Comptine dun autre ete Yann Tiersen official piano',
      'Portugal The Man Feel It Still official video',
      'Jon Bellion All Time Low official audio',
      'Cigarette Daydream Cage The Elephant official',
      'Cherry Wine Hozier official audio',
      'From Eden Hozier official audio',
      'Bloom The Paper Kites official audio',
      'Motion Picture Soundtrack Radiohead official',
      'Retrograde James Blake official audio',
    ],
  ),
  FeaturedPlaylist(
    id: 'mood_party',
    title: 'Party',
    subtitle: 'Turn it up loud',
    gradient: [Color(0xFFf953c6), Color(0xFFb91d73)],
    icon: Icons.celebration_rounded,
    emoji: '🎉',
    limitPerQuery: 1,
    searchQueries: [
      'Dynamite BTS official video',
      'Uptown Funk Bruno Mars official video',
      'Can\'t Stop The Feeling Justin Timberlake official',
      'Happy Pharrell Williams official video',
      'Telephone Lady Gaga Beyonce official video',
      'Party Rock Anthem LMFAO official video',
      'Shake It Off Taylor Swift official video',
      'Waka Waka Shakira official video',
      'Senorita Shawn Mendes Camila Cabello official',
      'Bad Guy Billie Eilish official video',
      'Blinding Lights The Weeknd official video',
      'Levitating Dua Lipa official video',
      'As It Was Harry Styles official video',
      'Butter BTS official video',
      'Permission To Dance BTS official video',
    ],
  ),
  FeaturedPlaylist(
    id: 'mood_focus',
    title: 'Focus',
    subtitle: 'Deep work, zero distraction',
    gradient: [Color(0xFF134E5E), Color(0xFF71B280)],
    icon: Icons.center_focus_strong_rounded,
    emoji: '🧠',
    limitPerQuery: 1,
    searchQueries: [
      'Clair de Lune Debussy official piano',
      'Gymnopédie No 1 Erik Satie official piano',
      'River Flows In You Yiruma official piano',
      'Nuvole Bianche Ludovico Einaudi official',
      'Experience Ludovico Einaudi official',
      'Divenire Ludovico Einaudi official',
      'Canon in D Pachelbel official classical',
      'Moonlight Sonata Beethoven official piano',
      'Für Elise Beethoven official piano',
      'Nocturne Op 9 No 2 Chopin official piano',
      'La Campanella Liszt official piano',
      'Prelude in C Major Bach official piano',
      'Air on the G String Bach official',
      'Goldberg Variations Bach official piano',
      'The Four Seasons Vivaldi Spring official',
    ],
  ),
];

// ─────────────────────────────────────────────────────────────────────────────
// Trending Now — search mode, limitPerQuery:1
// ─────────────────────────────────────────────────────────────────────────────

const kTrendingPlaylist = FeaturedPlaylist(
  id: 'trending_now',
  title: 'Trending Now',
  subtitle: 'What the world is playing today',
  gradient: [Color(0xFFFF6B6B), Color(0xFFFFD93D)],
  icon: Icons.trending_up_rounded,
  emoji: '🔥',
  limitPerQuery: 1,
  searchQueries: [
    'APT Rose Bruno Mars official video',
    'Die With A Smile Lady Gaga Bruno Mars official',
    'luther Kendrick Lamar SZA official',
    'Tere Vaaste Vicky Kaushal official audio',
    'Srivalli Pushpa official audio Sid Sriram',
    'Birds Of A Feather Billie Eilish official',
    'Good Luck Babe Chappell Roan official',
    'Kesariya Brahmastra official audio Arijit Singh',
    'Satranga Animal official audio Arijit Singh',
    'Espresso Sabrina Carpenter official video',
    'Too Sweet Hozier official audio',
    'Beautiful Things Benson Boone official video',
  ],
);
